import "./globals.css";
import { Nunito } from "next/font/google";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const font = Nunito({
	subsets: ["latin"],
});
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="scroll-smooth" data-theme="">
			<body className={` ${font.className}`}>
				{children}
				<script src="./assets/vendor/preline/dist/preline.js" defer></script>
			</body>
		</html>
	);
}
